name: CI

on:
  push:
    tags: v?.?.?

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: npm install
    - name: pack
      run: npm run pack
    - uses: actions/upload-artifact@v1
      with:
        name: extension.zip
        path: ./*.zip
